version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend_network

  ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    depends_on:
      - backend
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
